Per-vendor subdirectory (#378)
* Change NOT_VM_IMAGE -> DONT_COPY_COMMON

* Organize images into vendor subdirectories

* Handle common/ rel path

diff --git a/makefile.include b/makefile.include
--- a/makefile.include
+++ b/makefile.include
@@ -29,10 +29,16 @@ docker-build-common: docker-clean-build docker-pre-build
 	@if [ -z "$$IMAGE" ]; then echo "ERROR: No IMAGE specified"; exit 1; fi
 	@if [ "$(IMAGE)" = "$(VERSION)" ]; then echo "ERROR: Incorrect version string ($(IMAGE)). The regexp for extracting version information is likely incorrect, check the regexp in the Makefile or open an issue at https://github.com/hellt/vrnetlab/issues/new including the image file name you are using."; exit 1; fi
 	@echo "Building docker image using $(IMAGE) as $(REGISTRY)$(IMG_VENDOR)_$(IMG_NAME):$(VERSION)"
-ifeq ($(NOT_VM_IMAGE), 1)
-	echo "ok"
+ifeq ($(DONT_COPY_COMMON), 1)
+	echo "Don't need to copy common assets"
 else
-	cp ../common/* docker/
+	@if [ -d ../common ]; then \
+		cp ../common/* docker/; \
+	elif [ -d ../../common ]; then \
+		cp ../../common/* docker/; \
+	else \
+		echo "ERROR: Cannot find common directory"; exit 1; \
+	fi
 endif
 	@[ -f ./vswitch.xml ] && cp vswitch.xml docker/ || true
 	$(MAKE) IMAGE=$$IMAGE docker-build-image-copy
